version: '3.8'
services:
  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_PASSWORD: 354820
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build: .
    stdin_open: true
    command: ["python", "user_interface.py"]
    volumes:
      - .:/app
    ports:
      - "80"
    depends_on:
      - db
    tty: true

