version: '3.11.3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 354820
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build: .
    command: ["python", "user_interface.py"]
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - db
    tty: true

